### ISSUE TITLE
Fix Order layout

### ISSUE THREAD

**Issue by giacomomarongiu** [MassimoRomano/front-end-deliveboo#74]
- Colonna Sinistra: Dati e pagamento nella stessa colonna (Fixare il il form nel caso degli errori)
- Colonna Destra: Nome ristorante, riepilogo ordine, Carrello con possibilità di aumentare i piatti direttamente qui
- Cambiare bottone in "Paga Ora"
- Aggiustare validazione
- Aggiungere un loader nel pagamento

**Comment by MarioBroi** [comment]
Modifiche effetuate:
Colonne con form e pagamento
Altezza totale pagina
Bottone rinominato
Validazione numero telefonico (ora minimo 6 numeri per i telefoni fissi)

DA FARE:
Aggiungere un loader nel pagamento
Carrello con possibilità di aumentare i piatti direttamente qui
